name: Publish LayGenerator

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Tag Version
      id: version
      uses: battila7/get-version-action@v2

    - name: Publish Project
      run: dotnet publish "./src/LayGeneratorGUI/LayGeneratorGUI.csproj" --configuration Release --output ./LayGenerator --runtime win-x64 --self-contained /p:Version=${{ steps.version.outputs.version-without-v }} /p:PublishSingleFile=true

    - name: Zip Published Files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r LayGenerator-${{ steps.version.outputs.version }}.zip ./LayGenerator

    - name: Create Release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: LayGenerator-${{ steps.version.outputs.version }}.zip

    - name: Add Files To Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: LayGenerator-${{ steps.version.outputs.version }}.zip
        asset_name: LayGenerator-${{ steps.version.outputs.version }}.zip
        asset_content_type: application/zip

    # - name: Discord new release alert
