name: Publish LayGenerator

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Tag Version
      id: version
      uses: battila7/get-version-action@v2

    - name: Output Version
      run: echo ${{ steps.version.outputs.version-without-v }}

    - name: Publish Project
      run: dotnet publish "./src/LayGeneratorGUI/LayGeneratorGUI.csproj" --configuration Release --output ./Output --runtime win-x64 --self-contained /p:Version=${{ steps.version.outputs.version-without-v }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: LayGenerator
        path: ./Output

    
    # - name: Discord new release alert
