name: Publish LayGenerator

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Tag Version
      id: version
      uses: battila7/get-version-action@v2

    - name: Output Version
      run: echo ${{ steps.version.outputs.version-without-v }}

    - name: Publish Project
      run: dotnet publish "./src/LayGeneratorGUI/LayGeneratorGUI.csproj" --configuration Release --output ./Output --runtime win-x64 --self-contained /p:Version=${{ steps.version.outputs.version-without-v }} /p:PublishSingleFile=true

    # - name: Publish Artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: LayGenerator-${{ steps.version.outputs.version }}
    #     path: ./Output

    - name: Zip Published Files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r LayGenerator-${{ steps.version.outputs.version }}.zip ./Output

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: LayGenerator-${{ steps.version.outputs.version }}

    - name: Add Zipped Files To Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: LayGenerator-${{ steps.version.outputs.version }}.zip

    # - name: Discord new release alert
